spring.application.name=expense-tracker-api

server.port=8080

# PostgreSQL Database
spring.datasource.url=jdbc:postgresql://localhost:5432/expense_db
spring.datasource.username=postgres
spring.datasource.password=root
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Swagger Fix
spring.mvc.pathmatch.matching-strategy=ant_path_matcher

# MongoDB Atlas
spring.data.mongodb.uri=mongodb://root:root@ac-q9wdppm-shard-00-00.g8nu9pk.mongodb.net:27017,ac-q9wdppm-shard-00-01.g8nu9pk.mongodb.net:27017,ac-q9wdppm-shard-00-02.g8nu9pk.mongodb.net:27017/expense_db?ssl=true&replicaSet=atlas-njz91r-shard-0&authSource=admin&appName=Cluster0